### ISSUE TITLE
"INIT_SEQLEN" is not defined

### ISSUE THREAD

**Issue by successdang99** [CIA-Oceanix/TrAISformer#10]
trAISformer.py fails with: "INIT_SEQLEN" is not defined

What does "INIT_SEQLEN" mean?

**Comment by successdang99** [comment]
@dnguyengithub Please help me with this problem.

**Comment by duonginspace** [comment]
Hello, 
init_seqlen is "T+1" in the paper: https://arxiv.org/pdf/2109.03958.pdf
