### ISSUE TITLE
4-hot encoding vectors

### ISSUE THREAD

**Issue by danymrt** [CIA-Oceanix/TrAISformer#12]
Hello,
I'm trying to replicate the code of the paper but I notice that there isn't any function to make the 4-hot vectors. Do I miss something or in this work didn't you create and use these types of vectors?
@dnguyengithub

Thanks.

**Comment by duonginspace** [comment]
Hello, the code to create the 4-hot vectors can be found in function `to_indexes()` in `models.py`
