### ISSUE TITLE
NameError: name 'aisdls' is not defined

### ISSUE THREAD

**Issue by khavernathy** [CIA-Oceanix/TrAISformer#13]
When I run

```
python trAISformer.py
```

I get the below error:
```
Traceback (most recent call last):
  File "trAISformer.py", line 122, in <module>
    trainer.train()
  File ".../TrAISformer/trainers.py", line 270, in train
    seqs, masks, seqlens, mmsis, time_starts =  iter(aisdls["test"]).next()
NameError: name 'aisdls' is not defined
```

Should `aisdls` be defined somewhere in `trAISformer.py` ?

**Comment by duonginspace** [comment]
Hello, 
Did you run the code correctly? 
`aidls` is defined at line 104 of `trAISformer.py`
`        aisdls[phase] = DataLoader(aisdatasets[phase], 
                                   batch_size=cf.batch_size,
                                   shuffle=shuffle)`

**Comment by khavernathy** [comment]
thanks.

I had to pass `aisdls` along as a new argument `trainers.Trainer()` so that `trainers.py` could properly generate the output visualizations. This helped.

**Comment by duonginspace** [comment]
Hello,

Yes, you're right. Thank you for signaling that. I will fix it in the next update.
