### ISSUE TITLE
Prediction error with test data after training the neural network model 

### ISSUE THREAD

**Issue by prashanthoct74** [CIA-Oceanix/TrAISformer#16]
I am going through your research paper on ship trajectory route prediction,it's a conceptual research work through which i am learning a lot about ship route prediction.
But after training the neural network model with TrAISformer python code, Trajectory course predicted with test data provided is not a contiguous path for all mmsi trajectory provided in the test dataset. For example, 229879000,220289000 trajectory prediction of mmsi from test dataset , the predicted trajectory points are scattered .(attached screen shot of predicted output with your test data)

**Comment by duonginspace** [comment]
Hello, 
I don't see your attachment.

**Comment by prashanthoct74** [comment]
![220289000](https://user-images.githubusercontent.com/55191264/220669128-e73d221a-c7f1-49be-8613-b07d14565133.jpeg)
![229879000](https://user-images.githubusercontent.com/55191264/220669154-f202fbfa-35b9-430e-8d7d-a2d55bca3054.jpeg)

**Comment by duonginspace** [comment]
I continue this discussion in #17
