### ISSUE TITLE
Prediction error with test data after training the neural network model

### ISSUE THREAD

**Issue by prashanthoct74** [CIA-Oceanix/TrAISformer#17]
I am going through your research paper on ship trajectory route prediction,it's a conceptual research work through which i am learning a lot about ship route prediction.
But after training the neural network model with TrAISformer python code, Trajectory course predicted with test data provided is not a contiguous path for all mmsi trajectory provided in the test dataset. For example, 229879000,220289000 trajectory prediction of mmsi from test dataset , the predicted trajectory points are scattered .(attached screen shot of predicted output with your test data)
![220289000](https://user-images.githubusercontent.com/55191264/220670899-eec4bfe0-8780-403b-87de-52bb53df6707.jpeg)
![229879000](https://user-images.githubusercontent.com/55191264/220670921-e924c7d6-db22-4737-8908-7a63f677a3ae.jpeg)

**Comment by duonginspace** [comment]
Hello, 
It seems like your "4-hot" vectors are too coarse. 
What are the resolutions of your lat and lon bins?

**Comment by prashanthoct74** [comment]
Thank you for responding, i have trained neural network with same resolution as in code i.e, resolution of "4hot" vector is 0.01 degrees for both latitude and longitude attribute, so corresponding size of high dimensional vectors is 256 for both attributes.
But trained neural network is predicted as above in screen shot , can you guide where I am missing out anything.

**Comment by duonginspace** [comment]
Hello, 
Hmmm..., your output doesn't look right with the defined resolution. 
How many tracks do you have in the dataset?
Have you removed AIS observations whose distance to coastline is smaller than 1 nautical mile?

**Comment by duonginspace** [comment]
Closed due to inactivity.
