### ISSUE TITLE
About the.log file generated in the code

### ISSUE THREAD

**Issue by LNPU-GM** [CIA-Oceanix/TrAISformer#18]
Hello，Duong Nguyen
      I generated a.log file in the process of training the model. I saw that the code used the tesorboard visual tool, but I opened the.log file by tesorboard command could not be visualized at all. Is there something wrong with my approach? Or are.log files not visualized at all?
     Besides, I have checked tesorboard related knowledge in CSDN. According to the blog, tesorboard will generate a runs folder by default to store log files, but this folder is not generated after your code runs, I wonder whether it is normal?

This is a screenshot of the log file：
![image](https://user-images.githubusercontent.com/103182162/226372308-7cb01a75-6993-484d-89e8-f70d4bf885b4.png)
This is a screenshot of running a.log file with the command：
![image](https://user-images.githubusercontent.com/103182162/226372710-c11141ec-7db4-4f42-8481-e44926bae6e8.png)
This is a screenshot of what the browser shows：
![image](https://user-images.githubusercontent.com/103182162/226372932-9e4cfb69-af0e-4741-997e-3f5e56bbc14a.png)

Please give us your answer. Thank you very much!

**Comment by duonginspace** [comment]
Hello,

This is expected. I didn't log anything in tensorboard. 
You can modify the code to log the metrics/weights/figures that you're interested in. 
See: https://pytorch.org/tutorials/recipes/recipes/tensorboard_with_pytorch.html

Bests,
Duong
