### ISSUE TITLE
`cur_target >= 0 && cur_target < n_classes` failed.

### ISSUE THREAD

**Issue by zhangbingac** [CIA-Oceanix/TrAISformer#19]
when i  run trAISformer.py，an error occurred，how to solve it.

error:
023-04-01 14:38:36,484 - models - number of parameters: 5.742055e+07
  0%|          | 0/286 [00:00<?, ?it/s]C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [322,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [326,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [330,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [334,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [338,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [342,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [346,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.
C:\w\b\windows\pytorch\aten\src\ATen\native\cuda\Loss.cu:194: block: [1,0,0], thread: [350,0,0] Assertion `cur_target >= 0 && cur_target < n_classes` failed.

**Comment by zhangbingac** [comment]
@dnguyengithub

**Comment by duonginspace** [comment]
Hello, 
I cant reproduce the error
