### ISSUE TITLE
something about dataset

### ISSUE THREAD

**Issue by hhf-hd** [CIA-Oceanix/TrAISformer#20]
thanks for your great work ~
and i would like to know which dataset your use in this paper in the websites since there are many dataset .
i want to reprocedure the preprocess code and i want to compare my result with your pkl file so i should use the same dataset file like you.
thanks a lot for replying

![pic](https://user-images.githubusercontent.com/26891442/231464535-db6715ef-51ef-47be-b2ec-4edab0ed58a9.png)

**Comment by duonginspace** [comment]
Hello, 
You can find the DMA AIS data here: https://dma.dk/safety-at-sea/navigational-information/ais-data
Scroll down until the end and click on "Get historical data", which will lead you to http://web.ais.dk/aisdata/.
Good luck with your research!
