### ISSUE TITLE
Down-sample AIS trajectory data with a sampling rate of 10-minute

### ISSUE THREAD

**Issue by hhf-hd** [CIA-Oceanix/TrAISformer#22]
thanks a lot for your work !
and i would like to know some detail thing about Down-sample,
did you use the util.py in your GeoTrackNet  repo or some other method like pandas.resample ?

**Comment by duonginspace** [comment]
Hello, 
I use the function `interpolate` defined here https://github.com/CIA-Oceanix/GeoTrackNet/blob/master/utils.py to down-sample the data
