### ISSUE TITLE
The raw dataset (before preprocessing) comprises ∼712M AIS messages

### ISSUE THREAD

**Issue by zhangbingac** [CIA-Oceanix/TrAISformer#23]
thanks a lot for your work!
and i would like to know some detail thing about data
This data seems a bit small, because after my processing, the original data of more than 1 G has become about 80M, which is the data of one day. If it is multiplied by 90 days, it will greatly exceed 712M.
can you give me some details

**Comment by duonginspace** [comment]
Hello, 

What I wanted to say was there were ~712 **million** AIS messages.
