### ISSUE TITLE
about calculating as the haversine distance

### ISSUE THREAD

**Issue by zhangbingac** [CIA-Oceanix/TrAISformer#24]
thanks a lot for your work!

v_ranges = torch.tensor([2, 3, 0, 0]).to(cf.device)
v_roi_min = torch.tensor([model.lat_min, -7, 0, 0]).to(cf.device)

input_coords = (inputs * v_ranges + v_roi_min) * torch.pi / 180
pred_coords = (preds * v_ranges + v_roi_min) * torch.pi / 180

lat_min = 55.5
lat_max = 58.0
lon_min = 10.3
lon_max = 13

I don't understand why the v_ranges ,v_roi_min is not [2.5,2.7,0,0],[lat_min, lon_min],separately
can you give me some details

**Comment by zhangbingac** [comment]
@dnguyengithub

**Comment by duonginspace** [comment]
Hello. 
Sorry for the late reply. 

v_ranges ,v_roi_min are indeed [2.5,2.7,0,0],[lat_min, lon_min].

It's just bad code.
