### ISSUE TITLE
About the ploting part of data preprocessing

### ISSUE THREAD

**Issue by LeeJioky** [CIA-Oceanix/TrAISformer#27]
Hi, professor Duong Nguyen, I'd like to ask about the data preprocessing part in your GeoTrackNet repositry, as the picture shows, I followed your preprocessing steps with my own AIS data. But there are some problems with the final picuture, some trajectories pass through land or islands, which is incorrect. I double checked the preprocessing code but can't solve this problem, can you give me some ideas to solve the problem? I would be extremely grateful if you could reply~
![image](https://github.com/CIA-Oceanix/TrAISformer/assets/80331862/7d2119d8-d798-40e2-88d2-cd50b6be44c2)

**Comment by duonginspace** [comment]
Hello,

Apparently, the trajectories in your figure do not look correct. Could you verify that the maximum interval between two consecutive messages BEFORE THE RESAMPLING STEP is <= 2 hours?

I also highly recommend that you remove AIS observations within 1 nautical mile distance to the coastline. At port areas, the interactions between vessels highly affect their movement. TrAISformer was not designed for that.

**Comment by LeeJioky** [comment]
> Hello,
> 
> Apparently, the trajectories in your figure do not look correct. Could you verify that the maximum interval between two consecutive messages BEFORE THE RESAMPLING STEP is <= 2 hours?
> 
> I also highly recommend that you remove AIS observations within 1 nautical mile distance to the coastline. At port areas, the interactions between vessels highly affect their movement. TrAISformer was not designed for that.

Thank you for your reply~  
Yes, during the voyage splitting stage, the maximum interval between two consecutive messages has been split.

Removing AIS observations within 1 nautical mile from the coastline seems to be troublesome, and I did not find this part of the code in the preprocessing code of GeoTrackNet. Then I will select the selected area far away from the land later. In addition, I would like to ask you, if I select a larger selected space, and then the maximum time in the sample phase is no longer 20 hours, but a longer time, such as 5 days, will TrAISFormer or GeoTrackNet still work? Thank you~  : -)

**Comment by duonginspace** [comment]
One way check where the problem comes from is to select some abnormal tracks (e.g. those cross the land), plot the tracks before and after each step in the preprocessing script. 

> In addition, I would like to ask you, if I select a larger selected space, and then the maximum time in the sample phase is no longer 20 hours, but a longer time, such as 5 days, will TrAISFormer or GeoTrackNet still work? Thank you~ : -)

Yes both the models should work. 

Good luck!

**Comment by LeeJioky** [comment]
> Yes both the models should work.
> 
> Good luck!
thanks a lot~

**Comment by LeeJioky** [comment]
: -)
