### ISSUE TITLE
About the visualization of result prediction

### ISSUE THREAD

**Issue by ccbbzz** [CIA-Oceanix/TrAISformer#28]
Hi, professor Duong Nguyen,
I want to ask you about the visualization of the result data of your TrAISformer. I successfully ran trAISformer.py, but epoch_ Xx.jpg should be incorrect, such as longitude and latitude, and there is no original map. I checked the code carefully, but can't solve this problem, can you give me some ideas to solve the problem? I would be extremely grateful if you could reply!
![微信截图_20240124160332](https://github.com/CIA-Oceanix/TrAISformer/assets/136176843/6d83371a-4e34-4b5a-a2ef-8bc4dcf519f7)

**Comment by duonginspace** [comment]
Hello,

This is intended. 
epoch_ Xx.jpg are just intermediate plots to check the performance of the training. 
Lat and lon (as well as SOG and COG) are scaled to [0,1) in the training.
You have to "de-normalize" the lat and lon back to the original scale.
