### ISSUE TITLE
Rescaling during evaluation

### ISSUE THREAD

**Issue by buaa-luzhi** [CIA-Oceanix/TrAISformer#29]
[v_ranges](https://github.com/CIA-Oceanix/TrAISformer/blob/ebb904902b6264f872fff387f8ec9b00f0af135a/trAISformer.py#L129) presented in [model.lat_max - model.lat_min, model.lon_max - model.lon_min, 0, 0] = [2.5, 2.7, 0, 0].
[v_roi_min](https://github.com/CIA-Oceanix/TrAISformer/blob/ebb904902b6264f872fff387f8ec9b00f0af135a/trAISformer.py#L130) = [model.lat_min, 10.3, 0, 0]
@dnguyengithub
Is that right?

**Comment by duonginspace** [comment]
Hello,
Yes that's correct.
