### ISSUE TITLE
TrAISformer 0.48 0.94 1.64,The results in the paper cannot be reproduced

### ISSUE THREAD

**Issue by Zpp-hub** [CIA-Oceanix/TrAISformer#34]
After pulling down the code, I directly run trAISformer.py, but the results in the paper cannot be reproduced. Do I need to adjust any parameters?
![image](https://github.com/user-attachments/assets/a79cca5f-6a75-4a80-9d29-a3f23f1bf05f)

**Comment by duonginspace** [comment]
Hello,

No, you don’t need to change anything. You should be able to reproduce the results in the paper using the default parameters, as several others have successfully done.

Please note that:
![image](https://github.com/user-attachments/assets/0091c520-87a6-4b89-a718-3b2ac4e33a7f)
