### ISSUE TITLE
Paper: Non-contiguous vs Contiguous tracks & Downsampling

### ISSUE THREAD

**Issue by flxshk** [CIA-Oceanix/TrAISformer#4]
@dnguyengithub, 

In the paper, contiguous voyages are defined as those that have AIS pings with time deltas less than two hours. AIS trajectory data is also downsampled to a 10-minute frequency. (Page 5)

I would like to ask, how you generated location records in case of a time delta of more than 10 minutes and less than 2 hours.

Let's take voyage A as an example. At 8:00am we have an AIS ping. The next AIS ping is at 9:00am. So both pings would belong to the same voyage A. How do you generate the location, speed, and course at 8:10am, 8:20am, ... etc.?

**Comment by KaDnt** [comment]
In previous publications, the authors mention **linear interpolation** ("We re-sampled all voyages to a resolution of 10 minutes (i.e., {t + 1}− {t}= 10 mins) using a linear interpolation."  Nguyen D, Vadaine R, Hajduch G et al. (2021) GeoTrackNet--A Maritime Anomaly Detector Using Probabilistic Neural Network Representation of AIS Tracks and A Contrario Detection. IEEE Trans. Intell. Transport. Syst.:1–13. doi: 10.1109/TITS.2021.3055614) / **constant velocity model** ("[We] used constant velocity model to create regularly time-sampled AIS tracks at 10minute time scale." Nguyen D, Vadaine R, Hajduch G et al. A Multi-task Deep Learning Architecture for Maritime Surveillance using AIS Data Streams. In: IEEE 5th International Conference on Data Science and Advanced Analytics (DSAA), pp 331–340)
