### ISSUE TITLE
A question about data

### ISSUE THREAD

**Issue by cxl-ustb** [CIA-Oceanix/TrAISformer#5]
Hello,can you tell me that what's the meaning of that message in code ,"[9.17802000e-01, 1.48888889e-04, 4.83333333e-01, 2.32222222e-01,1.57006777e+09, 5.64739000e+08]",which I get in train.pkl file.Thank you very much.

**Comment by cxl-ustb** [comment]
Sorry,I have got it.

**Comment by IzayoiAster** [comment]
> Sorry,I have got it.

@cxl-ustb 请问数据的最后一列（5.64739000e+08）是什么意思呀😭

**Comment by IzayoiAster** [comment]
> > Sorry,I have got it.
> 
> @cxl-ustb 请问数据的最后一列（5.64739000e+08）是什么意思呀😭

草，没事了，我是傻逼

**Comment by khavernathy** [comment]
> Sorry,I have got it.

what was it?

**Comment by khavernathy** [comment]
@cxl-ustb

**Comment by IzayoiAster** [comment]
> > Sorry,I have got it.
> 
> what was it?

@khavernathy 就是mmsi……我当初盯了半天数据才看出来
