### ISSUE TITLE
Rescaling during evaluation

### ISSUE THREAD

**Issue by isaacOnline** [CIA-Oceanix/TrAISformer#7]
@dnguyengithub

When rescaling the variables to calculate error, why is [v_ranges](https://github.com/CIA-Oceanix/TrAISformer/blob/ebb904902b6264f872fff387f8ec9b00f0af135a/trAISformer.py#L129) set to [2, 3, 0, 0], and [v_roi_min](https://github.com/CIA-Oceanix/TrAISformer/blob/ebb904902b6264f872fff387f8ec9b00f0af135a/trAISformer.py#L130) set to [model.lat_min, -7, 0, 0]? Wouldn’t this rescale them to a different lat/lon range than the one you discuss in your paper? I would think they’d be [model.lat_max - model.lat_min, model.lon_max - model.lon_min, 0, 0] and [model.lat_min, model.lon_min, 0, 0], respectively. Or did you not use min/max scaling originally?

**Comment by duonginspace** [comment]
Hello, 
Sorry for the late reply.
You are right. 
In fact, with the ROI presented in [model.lat_max - model.lat_min, model.lon_max - model.lon_min, 0, 0] = [2, 3, 0, 0].
These values are (badly) hard-coded in the script.
