### ISSUE TITLE
hello, can you open the preprocess code? thanks!!!

### ISSUE THREAD

**Issue by njulocm** [CIA-Oceanix/TrAISformer#9]
@dnguyengithub

**Comment by duonginspace** [comment]
Hello, 
Sorry I mistakenly closed your issue. 
You can follow step-by-step the procedure presented in Section IV.A to preprocess the data: https://arxiv.org/pdf/2109.03958.pdf

You can also adapt this code:
https://github.com/CIA-Oceanix/GeoTrackNet/blob/master/data/csv2pkl.py
